// Code generated by "stringer -type=poolerError -linecomment -output pooler_generated.go"; DO NOT EDIT.

package kitchen

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[nilPoolable-0]
	_ = x[nilCreatorFunc-1]
	_ = x[nilAfterGetFunc-2]
	_ = x[nilPoolerToRecycler-3]
	_ = x[poolerDisabled-4]
	_ = x[recyclerDisabled-5]
	_ = x[initpoolerError-6]
}

const _poolerErrorCode_name = "nil Poolablenil New function passed to CreatePoolernil AfterGet function passed to CreatePoolernil Pooler passed to CreateRecyclerPooler disabledRecycler disablederror creating Recycler"

var _poolerErrorCode_index = [...]uint8{0, 12, 51, 95, 130, 145, 162, 185}

func (i poolerErrorCode) String() string {
	if i < 0 || i >= poolerErrorCode(len(_poolerErrorCode_index)-1) {
		return "poolerErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _poolerErrorCode_name[_poolerErrorCode_index[i]:_poolerErrorCode_index[i+1]]
}
